# Generated by Django 2.0 on 2018-12-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kickstarter',
            options={'ordering': ['backers_count']},
        ),
        migrations.RenameField(
            model_name='kickstarter',
            old_name='buckers_count',
            new_name='backers_count',
        ),
    ]
